# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [43]:
import torch

Construct a 5x3 matrix, uninitialized

In [44]:
x = torch.Tensor(5, 3)
print(x)

tensor([[3.5555e-15, 8.3097e-43, 9.1807e-01],
        [8.2987e-01, 4.8506e-01, 2.6671e-01],
        [1.6863e-01, 9.8689e-01, 1.5038e-02],
        [2.3219e-01, 7.0188e-01, 5.6231e-01],
        [6.0834e-01, 2.5375e-01, 1.1058e-01]])


Construct a randomly initialized matrix

In [45]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7161, 0.6776, 0.3387],
        [0.1803, 0.1816, 0.9591],
        [0.0669, 0.8019, 0.8254],
        [0.2234, 0.8930, 0.6810],
        [0.4968, 0.0679, 0.0983]])


Get its size

In [46]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [47]:
x[1:3] = 2
print(x)

tensor([[0.7161, 0.6776, 0.3387],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2234, 0.8930, 0.6810],
        [0.4968, 0.0679, 0.0983]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [48]:
y = torch.Tensor(2,17)
print(y)

tensor([[3.6372e-15, 8.3097e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [49]:
z = torch.FloatTensor(3, 1)
print(z)

tensor([[2.9200],
        [2.4553],
        [2.2938]])


In [50]:
t = torch.LongTensor(5,2,2)
print(t)

tensor([[[2547578506528,             0],
         [            0,             0]],

        [[            0,             0],
         [            0,             0]],

        [[            0,             0],
         [            0,             0]],

        [[            0,             0],
         [            0,             0]],

        [[            0,             0],
         [            0,             0]]])


In [51]:
y[:,:] = 7
print(y)

tensor([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])


In [52]:
y = torch.ByteTensor(5,)
print(y)

tensor([  0,   0, 224,  64, 226], dtype=torch.uint8)


In [53]:
y[1:4] = 1
print(y)

tensor([  0,   1,   1,   1, 226], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [54]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.4614, 1.2974, 0.4720],
        [2.8997, 2.5712, 2.2113],
        [2.5703, 2.8407, 2.9757],
        [0.2500, 1.2252, 1.3790],
        [1.2321, 0.6918, 1.0253]])


### 2.2 Addition: syntax 2

In [55]:
print(torch.add(x, y))

tensor([[1.4614, 1.2974, 0.4720],
        [2.8997, 2.5712, 2.2113],
        [2.5703, 2.8407, 2.9757],
        [0.2500, 1.2252, 1.3790],
        [1.2321, 0.6918, 1.0253]])


### 2.3 Addition: giving an output tensor

In [56]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.4614, 1.2974, 0.4720],
        [2.8997, 2.5712, 2.2113],
        [2.5703, 2.8407, 2.9757],
        [0.2500, 1.2252, 1.3790],
        [1.2321, 0.6918, 1.0253]])


### 2.4 Addition: in-place

adds `x`to `y`

In [57]:
y.add_(x)
print(y)

tensor([[1.4614, 1.2974, 0.4720],
        [2.8997, 2.5712, 2.2113],
        [2.5703, 2.8407, 2.9757],
        [0.2500, 1.2252, 1.3790],
        [1.2321, 0.6918, 1.0253]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [58]:
print(x[:, 1])

tensor([0.6776, 2.0000, 2.0000, 0.8930, 0.0679])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [70]:
a = torch.rand(2,4)
b = torch.rand(4,2)
result = torch.matmul(a,b)
print('a =', a)
print('b =', b)
print('result =', result)

a = tensor([[0.4758, 0.8286, 0.3824, 0.6440],
        [0.3667, 0.4714, 0.4578, 0.1090]])
b = tensor([[0.2923, 0.0134],
        [0.0682, 0.3337],
        [0.1569, 0.5614],
        [0.4753, 0.1821]])
result = tensor([[0.5617, 0.6148],
        [0.2630, 0.4390]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [59]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [60]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [61]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [71]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [63]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.7161, 0.6776, 0.3387],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2234, 0.8930, 0.6810],
        [0.4968, 0.0679, 0.0983]], device='cuda:0')
tensor([[1.4614, 1.2974, 0.4720],
        [2.8997, 2.5712, 2.2113],
        [2.5703, 2.8407, 2.9757],
        [0.2500, 1.2252, 1.3790],
        [1.2321, 0.6918, 1.0253]], device='cuda:0')
tensor([[2.1774, 1.9750, 0.8107],
        [4.8997, 4.5712, 4.2113],
        [4.5703, 4.8407, 4.9757],
        [0.4734, 2.1182, 2.0600],
        [1.7290, 0.7597, 1.1235]], device='cuda:0')
